/// <reference path="../packages/typescript-libs/meteor.d.ts" />
/// <reference path="../packages/typescript-libs/jquery.d.ts" />
/// <reference path="../common/model.d.ts" />
/// <reference path="../common/vassal.d.ts" />
/// <reference path="TypedSession.d.ts" />
/// <reference path="svg_zoom_and_pan.d.ts" />
/// <reference path="main.d.ts" />
/// <reference path="api/core.d.ts" />
declare function isTouchDevice(): boolean;
declare var main: Meteor.Template;
declare var welcome: Meteor.Template;
declare var play: Meteor.Template;
declare var pieces: Meteor.Template;
declare var controls: Meteor.Template;
