application: web-boards
version: 5
runtime: go
api_version: go1

handlers:
- url: /(.*)/
  static_files: static/\1/index.html
  upload: static/(.*)/index.html

- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /client
  static_dir: static/client

- url: /games
  static_dir: static/games

- url: /.*
  script: _go_app
